### ISSUE TITLE
Latest version of `babel-runtime` breaks dr-frankenstyle

### ISSUE THREAD

**Issue by sclevine** [pivotal-cf/dr-frankenstyle#1]
Running dr-frankenstyle with fresh node modules gives us this stack trace:
```
TypeError: undefined is not iterable!
    at TypeError (native)
    at assert (/Users/pivotal/workspace/github.com/pivotal-cf/our-repo/node_modules/dr-frankenstyle/node_modules/babel-runtime/node_modules/core-js/library/modules/$.assert.js:3:45)
    at module.exports.get (/Users/pivotal/workspace/github.com/pivotal-cf/our-repo/node_modules/dr-frankenstyle/node_modules/babel-runtime/node_modules/core-js/library/modules/$.iter.js:41:5)
    at callee$1$0$ (/Users/pivotal/workspace/github.com/pivotal-cf/our-repo/node_modules/dr-frankenstyle/dr-frankenstyle.js:69:23)
    at tryCatch (/Users/pivotal/workspace/github.com/pivotal-cf/our-repo/node_modules/dr-frankenstyle/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/pivotal/workspace/github.com/pivotal-cf/our-repo/node_modules/dr-frankenstyle/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/pivotal/workspace/github.com/pivotal-cf/our-repo/node_modules/dr-frankenstyle/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/pivotal/workspace/github.com/pivotal-cf/our-repo/node_modules/dr-frankenstyle/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at /Users/pivotal/workspace/github.com/pivotal-cf/our-repo/node_modules/dr-frankenstyle/node_modules/babel-runtime/regenerator/runtime.js:165:16
    at runMicrotasksCallback (node.js:337:7)
```
This is due to a new version of `babel-runtime` that the dr-frankenstyle `package.json` will pull down when you `npm install` it. We were able to add:
```
"devDependencies": {
   ...
    "babel-runtime": "=5.3.3",
   ...
},
```
to our own `package.json` to fix this temporarily. You may want to consider locking this version in the dr-frankenstyle `package.json` as well.

**Comment by gpleiss** [comment]
This is fixed in v0.1.6.
