### ISSUE TITLE
Error running CLI: Cannot read property 'dependencies' of undefined

### ISSUE THREAD

**Issue by sogko** [pivotal-cf/dr-frankenstyle#5]
Error:
```
TypeError: Cannot read property 'dependencies' of undefined
    at DependencyGraph.dependencies$ (/Users/hafiz/.nvm/versions/io.js/v1.8.1/lib/node_modules/dr-frankenstyle/dependency_graph.js:217:61)
    at tryCatch (/Users/hafiz/.nvm/versions/io.js/v1.8.1/lib/node_modules/dr-frankenstyle/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/hafiz/.nvm/versions/io.js/v1.8.1/lib/node_modules/dr-frankenstyle/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/hafiz/.nvm/versions/io.js/v1.8.1/lib/node_modules/dr-frankenstyle/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/hafiz/.nvm/versions/io.js/v1.8.1/lib/node_modules/dr-frankenstyle/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Users/hafiz/.nvm/versions/io.js/v1.8.1/lib/node_modules/dr-frankenstyle/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
    at /Users/hafiz/.nvm/versions/io.js/v1.8.1/lib/node_modules/dr-frankenstyle/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at process._tickCallback (node.js:341:15)
```

package.json (truncated)
```json
{
  "devDependencies": {
    "dr-frankenstyle": "^0.2.3"
  },
  "dependencies": {
    "alt": "^0.16.4",
    "babel-core": "^5.6.15",
    "babel-eslint": "^3.1.19",
    "babel-loader": "^5.2.2",
    "body-parser": "^1.9.3",
    "classnames": "^1.2.0",
    "crypto-browserify": "^3.9.14",
    "css-loader": "^0.14.1",
    "debug": "^2.2.0",
    "eslint": "^0.20.0",
    "eslint-loader": "^0.11.1",
    "eslint-plugin-react": "^2.2.0",
    "esprima-fb": "^15001.1.0-dev-harmony-fb",
    "express": "^4.12.3",
    "extract-text-webpack-plugin": "^0.7.0",
    "file-loader": "^0.8.1",
    "humanize": "0.0.9",
    "humanize-plus": "^1.5.0",
    "immutable": "^3.7.1",
    "iso": "^4.1.0",
    "jquery": "^2.1.3",
    "jscs-loader": "0.0.5",
    "json-loader": "^0.5.2",
    "jsonwebtoken": "^5.0.1",
    "jsx-loader": "^0.13.1",
    "jwt-client": "^0.1.2",
    "lodash": "^3.7.0",
    "method-override": "^2.3.1",
    "moment": "^2.10.3",
    "node-noop": "0.0.1",
    "node-sass": "^3.0.0-alpha.7",
    "pui-css-all": "^1.10.0",
    "qwest": "^1.6.0",
    "raw-loader": "^0.5.1",
    "react": "^0.13.1",
    "react-bootstrap-datetimepicker": "0.0.16",
    "react-components": "^0.2.0",
    "react-dropzone": "^1.2.2",
    "react-modal-component": "^1.0.9",
    "react-pagify": "^0.6.5",
    "react-popup": "^0.1.1",
    "react-router": "^0.13.2",
    "react-style-guide": "^1.1.4",
    "reactabular": "^0.5.2",
    "sass-loader": "^1.0.1",
    "socket.io": "^1.2.1",
    "style-loader": "^0.12.0",
    "superagent": "^1.2.0",
    "swig": "^1.4.2",
    "tcomb": "^1.0.3",
    "tcomb-form": "^0.5.3",
    "tcomb-validation": "^1.0.4",
    "url-loader": "^0.5.5",
    "velocity-animate": "^1.2.2",
    "webpack": "^1.4.13"
  }
}
```

**Comment by LePandaDuNet** [comment]
Hi,

I have the same problem. How do you have solve it?
Thanks,

Lisa
